class PopularDishesModel {
  String name;
  List<String> dishItems;
  double rating;
  double distance;
  int votes;
  var image;
  var price;
  String description;

  PopularDishesModel(
      {required this.name,
      required this.rating,
      required this.distance,
      required this.dishItems,
      required this.votes,
      required this.image,
      required this.price,
      required this.description});

  static List<PopularDishesModel> dishes = [
    PopularDishesModel(
        name: "Shaking Beef Ti-Trip",
        rating: 4.2,
        distance: 2.4,
        votes: 242,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/desert.png",
        price: 20.7,
        description: 'Best hot grilled beef and chips to increase flavors'),
    PopularDishesModel(
        name: "BBQ Rib Dinner",
        rating: 4.2,
        votes: 242,
        distance: 2.4,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/pancakes.png",
        price: 10.5,
        description: 'Delicious fried ribs and tomato sauce'),
    PopularDishesModel(
        name: "Fried Chicken Dinne",
        votes: 242,
        rating: 4.2,
        distance: 2.4,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/pancakes.png",
        price: 50.5,
        description: 'Best fried chicken with chips and mayonnaise'),
    PopularDishesModel(
        name: "Chicken Pizza",
        rating: 4.2,
        votes: 242,
        distance: 2.4,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/pizza.png",
        price: 10.5,
        description: 'Best hot grilled beef and chips to increase flavors'),
    PopularDishesModel(
        name: "Big Burger King",
        votes: 242,
        rating: 4.2,
        distance: 2.4,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/ramen.png",
        price: 5.5,
        description: 'Best hot grilled beef and chips to increase flavors'),
    PopularDishesModel(
        name: "Pepperoni Pizza",
        votes: 242,
        rating: 4.2,
        distance: 2.4,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/pizza.png",
        price: 8.5,
        description: 'Best hot grilled beef and chips to increase flavors'),
  ];
  static List<PopularDishesModel> moreDishes = [
    PopularDishesModel(
        name: "Shaking Beef Ti-Trip",
        rating: 4.2,
        distance: 2.4,
        votes: 242,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/desert.png",
        price: 20.7,
        description: 'Best hot grilled beef and chips to increase flavors'),
    PopularDishesModel(
        name: "BBQ Rib Dinner",
        rating: 4.2,
        votes: 242,
        distance: 2.4,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/pancakes.png",
        price: 10.5,
        description: 'Delicious fried ribs and tomato sauce'),
    PopularDishesModel(
        name: "Fried Chicken Dinne",
        votes: 242,
        rating: 4.2,
        distance: 2.4,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/pancakes.png",
        price: 50.5,
        description: 'Best fried chicken with chips and mayonnaise'),
    PopularDishesModel(
        name: "Chicken Pizza",
        rating: 4.2,
        votes: 242,
        distance: 2.4,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/pizza.png",
        price: 10.5,
        description: 'Best hot grilled beef and chips to increase flavors'),
    PopularDishesModel(
        name: "Big Burger King",
        votes: 242,
        rating: 4.2,
        distance: 2.4,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/ramen.png",
        price: 5.5,
        description: 'Best hot grilled beef and chips to increase flavors'),
    PopularDishesModel(
        name: "Pepperoni Pizza",
        votes: 242,
        rating: 4.2,
        distance: 2.4,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/pizza.png",
        price: 8.5,
        description: 'Best hot grilled beef and chips to increase flavors'),
    PopularDishesModel(
        name: "Shaking Beef Ti-Trip",
        rating: 4.2,
        distance: 2.4,
        votes: 242,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/desert.png",
        price: 20.7,
        description: 'Best hot grilled beef and chips to increase flavors'),
    PopularDishesModel(
        name: "BBQ Rib Dinner",
        rating: 4.2,
        votes: 242,
        distance: 2.4,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/pancakes.png",
        price: 10.5,
        description: 'Delicious fried ribs and tomato sauce'),
    PopularDishesModel(
        name: "Fried Chicken Dinne",
        votes: 242,
        rating: 4.2,
        distance: 2.4,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/pancakes.png",
        price: 50.5,
        description: 'Best fried chicken with chips and mayonnaise'),
    PopularDishesModel(
        name: "Chicken Pizza",
        rating: 4.2,
        votes: 242,
        distance: 2.4,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/pizza.png",
        price: 10.5,
        description: 'Best hot grilled beef and chips to increase flavors'),
    PopularDishesModel(
        name: "Big Burger King",
        votes: 242,
        rating: 4.2,
        distance: 2.4,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/ramen.png",
        price: 5.5,
        description: 'Best hot grilled beef and chips to increase flavors'),
    PopularDishesModel(
        name: "Pepperoni Pizza",
        votes: 242,
        rating: 4.2,
        distance: 2.4,
        dishItems: ["Burger", "Chicken", "Cake"],
        image: "images/home_screen/pizza.png",
        price: 8.5,
        description: 'Best hot grilled beef and chips to increase flavors'),
  ];
}
